markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

#gauges_id: 
google_analytics_id: UA-77759092-1
#google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

collections:
  docs:
    output: true

title: Symmetry Lab
name: Symmetry Lab • Biophysics of developing embryos
description: Biophysics of developing embryos
url: "https://sundar07.github.io/"
baseurl: "" # the subpath of your site, e.g. /blog/

twitter:
  username: Sundar_Ram_07

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
